name: Deploy sysstat offline

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target_machine:
          - vm-example@172.210.16.96:/root/
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Copy sshpass to /usr/local/bin
        run: |
          cp sshpass /usr/local/bin/
          chmod +x /usr/local/bin/sshpass

      - name: Deploy sysstat-offline folder to target machine
        run: |
          ls
          sudo /usr/local/bin/sshpass -p 'Yael1234567890' scp -o StrictHostKeyChecking=no -r sysstats-offline/ "${{ matrix.target_machine }}"
          sudo /usr/local/bin/sshpass -p 'Yael1234567890' ssh -o StrictHostKeyChecking=no "${{ matrix.target_machine }}" << 'EOF'
            if ! rpm -q sysstat; then
              cd /path/to/destination/sysstat-offline
              sudo rpm -Uvh lm_sensors-libs-3.4.0-23.20180522git70f7e08.el8.x86_64.rpm
              sudo rpm -Uvh sysstat-11.7.3-13.el8_10.x86_64.rpm
            else
              echo "sysstat is already installed."
            fi

            if ! systemctl is-active --quiet sysstat; then
              sudo systemctl start sysstat
            else
              echo "sysstat service is already running."
            fi
          EOF
