name: Deploy sysstat offline

on: push

jobs:
  deploy:
    runs-on: self-hosted
    strategy:
      matrix:
        target-machine:
          - name: "vm1"
            host: vm1-example@172.210.16.96:/root/
            ssh_password: 'Yael1234567890'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Transfer sysstat-offline folder
        run: |
          /usr/local/bin/sshpass -p "${{ matrix.target-machine.ssh_password }}" scp -r sysstat-offline/ "${{ matrix.target-machine.host }}"

      - name: Run commands on target machine
        run: |
          /usr/local/bin/sshpass -p "${{ matrix.target-machine.ssh_password }}" ssh "${{ matrix.target-machine.host }}" << 'EOF'
            if ! rpm -q sysstat; then
              cd /path/to/destination/sysstat-offline
              sudo rpm -Uvh lm_sensors.rpm sysstat.rpm
            else
              echo "sysstat is already installed."
            fi

            if ! systemctl is-active --quiet sysstat; then
              sudo systemctl start sysstat
            else
              echo "sysstat service is already running."
            fi
          EOF
