name: Deploy sysstat offline

on: push

jobs:
  deploy:
    runs-on: self-hosted
    strategy:
      matrix:
        target-machine:
          - vm-example@172.210.16.96:/root/

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Transfer sysstat-offline folder
        env:
          SSH_PASSWORD: 'Yael1234567890'
        run: |
          /usr/local/bin/sshpass -p "${SSH_PASSWORD}" scp -r sysstat-offline/ ${{ matrix.target-machine }}

      - name: Run commands on target machine
        env:
          SSH_PASSWORD: 'Yael1234567890'
        run: |
          /usr/local/bin/sshpass -p "${SSH_PASSWORD}" ssh ${{ matrix.target-machine }} << 'EOF'
            if ! rpm -q sysstat; then
              cd /path/to/destination/sysstat-offline
              sudo rpm -Uvh lm_sensors.rpm sysstat.rpm
            else
              echo "sysstat is already installed."
            fi

            if ! systemctl is-active --quiet sysstat; then
              sudo systemctl start sysstat
            else
              echo "sysstat service is already running."
            fi
          EOF
